export type VinylRecord = {
  id: number;
  title: string;
  artist: string;
  year: number;
  genre: string;
  price: number;
  condition: "Mint" | "Near Mint" | "Very Good Plus" | "Very Good" | "Good";
  description: string;
  image: string;
  inStock: boolean;
};

export const records: VinylRecord[] = [
  {
    id: 1,
    title: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    year: 1973,
    genre: "Progressive Rock",
    price: 34.99,
    condition: "Near Mint",
    description: "A landmark album in progressive rock history. Original UK pressing with excellent sonics.",
    image: "/covers/dark-side.svg",
    inStock: true,
  },
  {
    id: 2,
    title: "Kind of Blue",
    artist: "Miles Davis",
    year: 1959,
    genre: "Jazz",
    price: 42.99,
    condition: "Very Good Plus",
    description: "The best-selling jazz album of all time. Modal jazz at its finest.",
    image: "/covers/kind-of-blue.svg",
    inStock: true,
  },
  {
    id: 3,
    title: "Rumours",
    artist: "Fleetwood Mac",
    year: 1977,
    genre: "Rock",
    price: 28.99,
    condition: "Very Good Plus",
    description: "One of the best-selling albums of all time with pristine sound quality.",
    image: "/covers/rumours.svg",
    inStock: true,
  },
  {
    id: 4,
    title: "Abbey Road",
    artist: "The Beatles",
    year: 1969,
    genre: "Rock",
    price: 54.99,
    condition: "Near Mint",
    description: "The final studio album recorded by The Beatles. Stunning audio fidelity.",
    image: "/covers/abbey-road.svg",
    inStock: true,
  },
  {
    id: 5,
    title: "Blue",
    artist: "Joni Mitchell",
    year: 1971,
    genre: "Folk",
    price: 31.99,
    condition: "Very Good Plus",
    description: "Considered one of the greatest albums ever made. Raw emotional songwriting.",
    image: "/covers/blue.svg",
    inStock: false,
  },
  {
    id: 6,
    title: "Thriller",
    artist: "Michael Jackson",
    year: 1982,
    genre: "Pop",
    price: 24.99,
    condition: "Very Good",
    description: "The best-selling album of all time. Original US pressing in great shape.",
    image: "/covers/thriller.svg",
    inStock: true,
  },
  {
    id: 7,
    title: "What's Going On",
    artist: "Marvin Gaye",
    year: 1971,
    genre: "Soul",
    price: 38.99,
    condition: "Near Mint",
    description: "A concept album addressing social issues. Marvin Gaye's masterpiece.",
    image: "/covers/whats-going-on.svg",
    inStock: true,
  },
  {
    id: 8,
    title: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    year: 1971,
    genre: "Hard Rock",
    price: 39.99,
    condition: "Very Good Plus",
    description: "Contains Stairway to Heaven. One of the greatest rock albums ever pressed.",
    image: "/covers/led-zeppelin-iv.svg",
    inStock: true,
  },
  {
    id: 9,
    title: "Purple Rain",
    artist: "Prince",
    year: 1984,
    genre: "Pop/Rock",
    price: 29.99,
    condition: "Near Mint",
    description: "Soundtrack to the film. Prince at the peak of his powers.",
    image: "/covers/purple-rain.svg",
    inStock: true,
  },
  {
    id: 10,
    title: "Nevermind",
    artist: "Nirvana",
    year: 1991,
    genre: "Grunge",
    price: 26.99,
    condition: "Very Good Plus",
    description: "Changed the course of rock music. Original DGC pressing.",
    image: "/covers/nevermind.svg",
    inStock: false,
  },
  {
    id: 11,
    title: "Tapestry",
    artist: "Carole King",
    year: 1971,
    genre: "Pop",
    price: 27.99,
    condition: "Very Good",
    description: "One of the all-time greats. Warm analog sound.",
    image: "/covers/tapestry.svg",
    inStock: true,
  },
  {
    id: 12,
    title: "Horses",
    artist: "Patti Smith",
    year: 1975,
    genre: "Punk",
    price: 44.99,
    condition: "Near Mint",
    description: "The debut album that defined punk poetry. Rare original pressing.",
    image: "/covers/horses.svg",
    inStock: true,
  },
];

export const genres = ["All", ...Array.from(new Set(records.map((r) => r.genre)))];
